site_name: 'YWAM Sendai Wiki'
site_url: https://wiki.ywamsendai.org
site_author: 'YWAM Sendai'
site_description: 'Learn about YWAM Sendai'
repo_name: '/ywamsendai-wiki'
repo_url: https://github.com/ywamsendai/ywamsendai-wiki/
edit_uri: edit/master/docs/
docs_dir: docs

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  language: 'en'
  
google_analytics: ['UA-20132770-3', 'ywamsendai.org']

extra:
    social:
    - type: 'comment-o'
      link: 'https://www.ywamsendai.org'
    - type: 'medium'
      link: 'https://medium.com/ywamsendai'
    - type: 'twitter'
      link: 'https://twitter.com/ywamsendai'
    - type: 'github'
      link: 'https://github.com/ywamsendai'
    - type: 'facebook'
      link: 'https://facebook.com/ywamsendai'

nav:
    - Welcome: 'index.md'
    - YWAM:
        - Why Japan?: 'ywam/whyjapan.md'
        - Join: 'ywam/join.md'
        - Finances: 'ywam/finances.md'
        - Fundraising: 'ywam/fundraising.md'
        - Purpose, Beliefs & Values: 'ywam/values.md'
        - Vision: 'ywam/vision.md'
        - Tools: 'ywam/tools.md'
    - Life in Japan:
        - Culture: 'lifeinjapan/culture.md'
        - Language: 'lifeinjapan/language.md'
        - Getting Settled: 'lifeinjapan/gettingsettled.md'
        - Phones: 'lifeinjapan/phones.md'
