# Project information
site_name: YWAM Sendai Wiki
site_url: https://wiki.ywamsendai.org
site_author: YWAM Sendai
site_description: Learn about YWAM Sendai

# Repository
repo_name: ywamsendai/ywamsendai-wiki
repo_url: https://github.com/ywamsendai/ywamsendai-wiki/
edit_uri: edit/master/docs/
docs_dir: docs

# Copyright
copyright: Copyright &copy; 2020 YWAM Sendai

theme:
  name: material

    # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
    social:
    - icon: fontawesome/regular/comment
      link: https://www.ywamsendai.org
    - icon: fontawesome/brands/medium
      link: https://medium.com/ywamsendai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ywamsendai
    - icon: fontawesome/brands/github
      link: https://github.com/ywamsendai
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/ywamsendai

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ywamsendai
      repo: ywamsendai-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Welcome: index.md
    - YWAM:
        - About YWAM International: ywam/ywam.md
        - Purpose, Beliefs & Values: ywam/values.md
        - Legacy Words & Covenants : ywam/covenants.md
        - About YWAM Sendai: ywam/ywamsendai.md
        - Why Japan?: ywam/whyjapan.md
        - Life in YWAM Sendai: ywam/ywamsendailife.md
        - Tools: ywam/tools.md
        - End Bible Poverty Now: ywam/endbiblepoverty.md
        - Donate: ywam/donate.md
    - Join Us:
        - Onboarding Process: ywam/join.md
        - Staff Expectations: ywam/commitments.md
        - Staff Terms & Conditions: ywam/terms.md
        - Finances: ywam/finances.md
        - Fundraising: ywam/fundraising.md
        - Visa: ywam/visa.md
    - Life in Japan:
        - Culture: lifeinjapan/culture.md
        - Language: lifeinjapan/language.md
        - Getting Settled: lifeinjapan/gettingsettled.md
        - Disaster Preparation: lifeinjapan/disaster.md
        - Phones: lifeinjapan/phones.md
        - Waste System: lifeinjapan/waste.md


# Google Analytics
google_analytics: ['UA-20132770-5', 'wiki.ywamsendai.org']
